### PR TITLE
Call Player.onData when event emitted

### PR DESCRIPTION
**Pull request by MoyuScript**
Just simply call Player.onData when midi event emitted

### CODE REVIEW

**Comment by jazz-soft** [comment]
Hi! Thank you for the commit!

It looks like the function onData() is obsolete for long time, and I just forgot to remove it.
What do you want to use it for?

**Comment by Passkou** [comment]
I want to handle midi events by myself. For example, when Note on event is emitting, show some particles or print name of playing note.

**Comment by jazz-soft** [comment]
You can watch the events on the player output,
e.g.:
````
player.connect(function(msg) {
  console.log(msg);
});
````

**Comment by Passkou** [comment]
Thank you!

**Comment by Passkou** [comment]
By the way, some midi file may have different bpm in different parts of the song because of the 'SetTempoEvent'. But this module dosen't seem to be able to handle them. There is only a constant bpm during playing. How can i resolve this probrom?

**Comment by jazz-soft** [comment]
Please send me the file or point me to the URL, I'll take a look.
Thanks!

**Comment by Passkou** [comment]
A simple midi demo that make by fl studio (base64)
```
TVRoZAAAAAYAAQADAGBNVHJrAAAADAD/WAQEAhgIAP8vAE1UcmsAAAA5AP9RAwaKGwD/UQMGihsA/1EDBoobgwD/UQMNx8eDAP9RAxJBk4MA/1EDC5B6gwD/UQMGihsA/y8ATVRyawAAASMA/wMITUlESSBPdXQAsApAALAHZADgAEAAsGUAALBkAACwBgwAsApAALAHZADgAEAAwAAAsGUAALBkAACwBgwAsApAALAHZADgAEAAwAAAkDxkALBlAACwZAAAsAYMALAKQACwB2QA4ABAAMAAYIA8QACQPmRggD5AAJBAZGCAQEAEkEFkXJA8ZASAQUBcgDxAAJA+ZGCAPkAAkEBkYIBAQACQQWRggEFAAJA8ZGCAPEAAkD5kYIA+QACQQGRggEBAAJBBZGCAQUAAkDxkYIA8QACQPmRggD5AAJBAZGCAQEAAkEFkX4BBQAGwZQAAsGQAALAGDACwCkAAsAdkAOAAQADAAAGwZQAAsGQAALAGDACwCkAAsAdkAOAAQADAAAD/LwA=
```
图片

**Comment by jazz-soft** [comment]
The problem with your MIDI file is that the tempo change messages are in the second track.
In Type 1 MIDI file all tempo changes must be in the first track.

```
SMF:
  type: 1
  ppqn: 96
  tracks: 3
MTrk:
  0: ff58 -- Time Signature: 4/4 24 8
  0: ff2f -- End of Track
MTrk:
  0: ff51 -- Tempo: 140 bpm
  0: ff51 -- Tempo: 140 bpm
  0: ff51 -- Tempo: 140 bpm
  384: ff51 -- Tempo: 66.44 bpm
  768: ff51 -- Tempo: 50.15 bpm
  1152: ff51 -- Tempo: 79.17 bpm
  1536: ff51 -- Tempo: 140 bpm
  1536: ff2f -- End of Track
MTrk:
  0: ff03 -- Sequence Name: MIDI Out
  0: b0 0a 40 -- Pan MSB
  0: b0 07 64 -- Channel Volume MSB
  0: e0 00 40 -- Pitch Wheel
  0: b0 65 00 -- Registered Parameter Number MSB
  0: b0 64 00 -- Registered Parameter Number LSB
  0: b0 06 0c -- Data Entry MSB
  0: b0 0a 40 -- Pan MSB
  0: b0 07 64 -- Channel Volume MSB
  0: e0 00 40 -- Pitch Wheel
  0: c0 00 -- Program Change
  0: b0 65 00 -- Registered Parameter Number MSB
  0: b0 64 00 -- Registered Parameter Number LSB
  0: b0 06 0c -- Data Entry MSB
  0: b0 0a 40 -- Pan MSB
  0: b0 07 64 -- Channel Volume MSB
  0: e0 00 40 -- Pitch Wheel
  0: c0 00 -- Program Change
  0: 90 3c 64 -- Note On
  0: b0 65 00 -- Registered Parameter Number MSB
  0: b0 64 00 -- Registered Parameter Number LSB
  0: b0 06 0c -- Data Entry MSB
  0: b0 0a 40 -- Pan MSB
  0: b0 07 64 -- Channel Volume MSB
  0: e0 00 40 -- Pitch Wheel
  0: c0 00 -- Program Change
  96: 80 3c 40 -- Note Off
  96: 90 3e 64 -- Note On
  192: 80 3e 40 -- Note Off
  192: 90 40 64 -- Note On
  288: 80 40 40 -- Note Off
  292: 90 41 64 -- Note On
  384: 90 3c 64 -- Note On
  388: 80 41 40 -- Note Off
  480: 80 3c 40 -- Note Off
  480: 90 3e 64 -- Note On
  576: 80 3e 40 -- Note Off
  576: 90 40 64 -- Note On
  672: 80 40 40 -- Note Off
  672: 90 41 64 -- Note On
  768: 80 41 40 -- Note Off
  768: 90 3c 64 -- Note On
  864: 80 3c 40 -- Note Off
  864: 90 3e 64 -- Note On
  960: 80 3e 40 -- Note Off
  960: 90 40 64 -- Note On
  1056: 80 40 40 -- Note Off
  1056: 90 41 64 -- Note On
  1152: 80 41 40 -- Note Off
  1152: 90 3c 64 -- Note On
  1248: 80 3c 40 -- Note Off
  1248: 90 3e 64 -- Note On
  1344: 80 3e 40 -- Note Off
  1344: 90 40 64 -- Note On
  1440: 80 40 40 -- Note Off
  1440: 90 41 64 -- Note On
  1535: 80 41 40 -- Note Off
  1536: b0 65 00 -- Registered Parameter Number MSB
  1536: b0 64 00 -- Registered Parameter Number LSB
  1536: b0 06 0c -- Data Entry MSB
  1536: b0 0a 40 -- Pan MSB
  1536: b0 07 64 -- Channel Volume MSB
  1536: e0 00 40 -- Pitch Wheel
  1536: c0 00 -- Program Change
  1537: b0 65 00 -- Registered Parameter Number MSB
  1537: b0 64 00 -- Registered Parameter Number LSB
  1537: b0 06 0c -- Data Entry MSB
  1537: b0 0a 40 -- Pan MSB
  1537: b0 07 64 -- Channel Volume MSB
  1537: e0 00 40 -- Pitch Wheel
  1537: c0 00 -- Program Change
  1537: ff2f -- End of Track
```

**Comment by Passkou** [comment]
Thank you for your patience.
This midi file was exported by FL STUDIO 20. I also tried another module like [MidiPlayerJS](http://grimmdude.com/MidiPlayerJS/docs/) and that is worked correctly. I also tried MIDITrail to play this midi file and also worked.
So maybe you could consider to fix this bug?

**Comment by jazz-soft** [comment]
Technically, it's FL STUDIO 20 developer who have to fix the bug.
See the specs at https://www.midi.org/downloads?task=callelement&format=raw&item_id=92&element=f85c494b-2b32-4109-b8c1-083cca2b7db6&method=download
However, I'm going to allow the tempo changes in wrong tracks in the next release.
Thank you for the idea!
spec

**Comment by jazz-soft** [comment]
I've committed a new version. Please give it a try. (it's not published on npm yet).
Thanks again!

**Comment by Passkou** [comment]
It's now can works perfectly. Thank you very much!

**Pull request closed without merging**
